### ISSUE TITLE
Unable to run/install nokogiri-1.8.0

### ISSUE THREAD

**Issue by DarrenRainey** [verluchie/termux-metasploit#5]
An error occurred while installing nokogiri (1.8.0), and Bundler cannot
continue.

Make sure that `gem install nokogiri -v "1.8.0"` succeeds before bundling.
In Gemfile:
  factory_girl_rails was resolved to 4.8.0, which depends on
    railties was resolved to 4.2.9, which depends on
      actionpack was resolved to 4.2.9, which depends on
        actionview was resolved to 4.2.9, which depends on
          rails-dom-testing was resolved to 1.0.8, which depends on
            nokogiri

**Comment by kiyao** [comment]
I have the same problem!

**Comment by duncanxxx** [comment]
Did you fix the problem you had,been trying to fix but in vain,any help will be appreciated.

**Comment by DarrenRainey** [comment]
I got it to work on a different device from what I can tell it looks like it was running out of memory/RAM during setup which caused it to fail so maybe if you add a swap file or something while installing it should work fine.

**Comment by duncanxxx** [comment]
./msfconsole: No such file or directory
$ ./README.md
bash: ./README.md: Permission denied
$ msfconsole
Could not find nokogiri-1.8.0 in any of the sources
Run `bundle install` to install missing gems.was trying to install it on an Android device.i don't know if it can install properly without running into that error

**Comment by DarrenRainey** [comment]
you can install it via apt which may work better for some people::
```
pkg install unstable-repo
pkg install metasploit
```

**Comment by duncanxxx** [comment]
Thank you ,going to try it out

**Comment by duncanxxx** [comment]
Hi, thanks for the help, it finally worked, installed it and it works
fine,needed help about a package called Sherlock, any info will be
appreciated.thanks

**Comment by DarrenRainey** [comment]
> Hi, thanks for the help, it finally worked, installed it and it works fine,needed help about a package called Sherlock, any info will be appreciated.thanks

I think you should open a separate issue for that since I'm going to consider this as resolved now.

**Comment by duncanxxx** [comment]
Alright thank you

**Comment by jayanp7** [comment]
Getting error code 1 please help
me
